"""Writes ../validation/VALIDATION_REPORT.md from automated_checks.json and reference_values.csv."""
import os, json
import pandas as pd
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
R = json.load(open(os.path.join(ROOT, 'validation', 'automated_checks.json')))
ref = pd.read_csv(os.path.join(ROOT, 'validation', 'reference_values.csv'))
def v(m, ctx='Overall (Jan–Sep 2026)', mem=None, pct=False, dp=1):
    x = ref[(ref.Measure == m) & (ref.Context == ctx)]
    if mem is not None: x = x[x.Member == mem]
    val = x.ExpectedValue.iloc[0]
    if pd.isna(val): return '(blank)'
    return f'{val*100:.{dp}f}%' if pct else f'{val:,.{dp if val % 1 else 0}f}'
P = sum(r['outcome'] == 'PASS' for r in R)
L = ['# Validation report', '',
     f'Generated by `scripts/write_validation_report.py`. **Automated: {P} of {len(R)} tests passed.** '
     'Tests that need Power BI Desktop could not be run in the build environment. They are listed in §3 as **NOT RUN** with the expected results to check, and none of them is claimed as passed.', '',
     '## 1. Automated tests (performed)', '', '| ID | Area | Test | Outcome | Detail |', '|---|---|---|---|---|']
for r in R: L.append(f"| {r['id']} | {r['area']} | {r['test']} | **{r['outcome']}** | {r['detail'] or '–'} |")
L += ['', '## 2. Reference values (performed)', '',
      f'`reference_values.csv` holds {len(ref):,} expected values. Every numeric measure is evaluated overall, by month, by quarter, by adopter and by zone, plus MoM/QoQ, by an independent pandas implementation. Headline checks:', '',
      '| Measure | Expected | Matches validated source workbook? |', '|---|---|---|',
      f"| General Attendance, Jan–Sep | {v('General Attendance')} | yes (Monthly_Indicator_Table) |",
      f"| General Attendance QoQ %, Q3 2026 | {v('General Attendance QoQ %', 'Quarter', 'Q3 2026', pct=True)} | yes (source: −8.5%) |",
      f"| Reporting Completeness % (Q1 / Q2 / Q3) | {v('Reporting Completeness %', 'Quarter', 'Q1 2026', True)} / {v('Reporting Completeness %', 'Quarter', 'Q2 2026', True)} / {v('Reporting Completeness %', 'Quarter', 'Q3 2026', True)} | yes |",
      f"| U5 Malaria Test Positivity %, Q3 | {v('U5 Malaria Test Positivity %', 'Quarter', 'Q3 2026', True)} | yes (source: 72.3%) |",
      f"| Deaths per 100 Reports, Q2 | {v('Deaths per 100 Reports', 'Quarter', 'Q2 2026')} | yes (source: 19.2) |",
      f"| FP Method Acceptances, Q1 | {v('FP Method Acceptances (All Methods)', 'Quarter', 'Q1 2026')} | **intentional difference**: source shows 0; fields did not exist (NULL) |", '',
      '## 3. Power BI Desktop tests – NOT RUN (environment had no Power BI Desktop)', '',
      'Run these after building the report; record the outcome and initials in the last column.', '',
      '| ID | Test | How | Expected result | Outcome |', '|---|---|---|---|---|',
      '| B1 | Queries load without errors | Close & Apply | 8 tables + DimDate load; row counts 14,580 / 540 / 45 / 315 / 60 / 4 / 7 / 32 / 365 | NOT RUN |',
      '| B2 | Measures compile | Load `measures.dax` | 84 measures, no syntax errors (static lint passed – see D1) | NOT RUN |',
      '| B3 | Measure values match references | DAX Studio: `dax_validation_queries.dax` | Every value equals `reference_values.csv` (rounding only) | NOT RUN |',
      f"| B4 | Month slicer | Select September only | General Attendance {v('General Attendance', 'Month', '2026-09-01')}; Reporting Completeness {v('Reporting Completeness %', 'Month', '2026-09-01', True)} | NOT RUN |",
      f"| B5 | Quarter slicer | Select Q2 2026 | General Attendance {v('General Attendance', 'Quarter', 'Q2 2026')}; Immunization Doses {v('Immunization Doses <1 Year', 'Quarter', 'Q2 2026')} | NOT RUN |",
      f"| B6 | Adopter slicer | Select Adopter B | Reporting Completeness {v('Reporting Completeness %', 'Adopter', 'Adopter B', True)}; General Attendance {v('General Attendance', 'Adopter', 'Adopter B')}; mortality visuals blank | NOT RUN |",
      f"| B7 | Zone slicer | Select South South | Reporting Completeness {v('Reporting Completeness %', 'Zone', 'South South', True)}; General Attendance {v('General Attendance', 'Zone', 'South South')} | NOT RUN |",
      '| B8 | No-records combination | Adopter B + Month = July | Volume cards blank (not 0); narrative reads "No facility reports match…"; Reporting Completeness 0.0% | NOT RUN |',
      '| B9 | Missing ≠ zero in visuals | Facility drill-through on any Adopter B facility | Months without a report show gaps, not zeros | NOT RUN |',
      '| B10 | Reset | Click Reset bookmark | All slicers cleared; values equal the Overall reference row | NOT RUN |',
      '| B11 | Service-category slicer | Select "Malaria" on page 1 | KPI cards unchanged (they pin their indicator); composition chart unaffected (interaction off) | NOT RUN |',
      '| B12 | MoM / QoQ | Monthly axis | General Attendance MoM % for June = ' + v('General Attendance MoM %', 'Month', '2026-06-01', True) + '; January blank | NOT RUN |',
      '| B13 | Privacy in report metadata | Inspect tooltips, drill-through, *See records*, bookmarks, Export data, File › Info | Only pseudonyms; no file paths to the raw workbook in query metadata | NOT RUN |',
      '| B14 | Visual QA | Review each page at 100% zoom | No clipped titles or labels, axes start at zero, units in titles, no red/green-only encodings | NOT RUN |',
      '| B15 | Screenshots | Export each page | No confidential information visible | NOT RUN |', '',
      '## 4. Unresolved issues and limitations', '',
      '1. **The `.pbix` and the screenshots don\'t exist yet.** Power BI Desktop was unavailable, so tests B1–B15 are pending.',
      '2. **The DAX was checked statically, not executed.** The lint confirms syntax balance and that every reference resolves. Values were verified with an independent implementation, not with the DAX engine.',
      '3. **Residual re-identification risk at adopter level**, from facility counts and patterns (see DATA_PREPARATION.md §2). Clearance from the data owner is required before public release.',
      '4. **Source limitations carried forward:** September is partial; June is spiked; one adopter has non-response; immunization is counted as doses; cross-sectional ANC ratios; mortality is an upper bound; no population denominators or targets.']
open(os.path.join(ROOT, 'validation', 'VALIDATION_REPORT.md'), 'w').write('\n'.join(L) + '\n')
print('report written', P, len(R))
